/*
 * Copyright 2012-2013 Ontology Engineering Group, Universidad Politécnica de Madrid, Spain
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package DataStructures;

import Static.GeneralConstants;
import DataStructures.GraphNode.GraphNode;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;

/**
 * A class representing a Graph to represent templates, traces and fragments.
 * The Graph has an arraylist with the URIs, a HashMap with the URI and the 
 * graph node associated to it (with the type, the number of the node in the graph
 * and the URI) and an adjacency matrix with the adjacencies among nodes.
 * @author Daniel Garijo
 */
public class Graph {
    //we have the URIs just for the purpose of making the processing easier (it is easier
    //to processs an arrayList than a hashMap
    private ArrayList<String> URIs;
    private HashMap<String,GraphNode> nodes;    
    //it is an String adjacency Matrix so we know the type of relationship
    //that is connecting 2 nodes. No more than 1 relation connects 2 nodes.
    private String [][] adjacencyMatrix;
    private String name;//note: the name is often the URI.

    /**
     * Basic constructor
     */
    public Graph() {
        URIs = new ArrayList<String>();
        nodes = new HashMap<String, GraphNode>();
    }

    /**
     * Advanced constructor
     * @param URIs URIs of the entities in the graph
     * @param nodes nodes correspondent to the URIs. Necessary because each URI
     * has a type, a number (with the position in the adjacency matrix) and 
     * optional metadata associated to each particular system.
     * @param adjacencyMatrix with the connections among different URIs.
     * @param name the name of the current graph
     */
    public Graph(ArrayList<String> URIs, HashMap<String, GraphNode> nodes, String[][] adjacencyMatrix, String name) {
        this.URIs = URIs;
        this.nodes = nodes;
        this.adjacencyMatrix = adjacencyMatrix;
        this.name = name;
    }
    
    /**
     * Function that returns the number of nodes in a graph (URIs.size)
     * @return size of the URIs arrayList
     */
    public int getNumberOfNodes(){
        return URIs.size();
    }

    /**
     * Getter of the adjacency matrix
     * @return adjacency matrix
     */
    public String[][] getAdjacencyMatrix() {
        return adjacencyMatrix;
    }

    /**
     * Getter of the name of the graph
     * @return the name of the graph
     */
    public String getName() {
        return name;
    }
    
    /**
     * Getter of the nodes of the graph
     * @return nodes of the graph
     */
    public HashMap<String, GraphNode> getNodes() {
        return nodes;
    }

    /**
     * Getter of the URIs of the graph
     * @return URIs in the graph
     */
    public ArrayList<String> getURIs() {
        return URIs;
    }
    
    /**
     * Setter of the nodes of the graph
     * @param newNodes new nodes
     * @param newURIs new URIs
     */
    public void setNodes(HashMap<String,GraphNode> newNodes, ArrayList<String> newURIs){
        nodes = newNodes;
        URIs = newURIs;
    }

    /**
     * Setter of the adjacency matrix
     * @param adjacencyMatrix new adjacency matrix
     */
    public void setAdjacencyMatrix(String[][] adjacencyMatrix) {
        this.adjacencyMatrix = adjacencyMatrix;        
    }

    /**
     * Name setter
     * @param name new name of the graph 
     */
    public void setName(String name) {
        this.name = name;
    }
    
    /**
     * Given a graph with used and wasGeneratedBy dependencies, this method
     * simplifies the connections by adding the "wasInformedBy" property between 
     * different processes. It does collide with any of the aforementioned properties,
     * as used only happens between activities and artifact and wasGenerated by 
     * only happens between artifacts and activities.
     * 
     * Method used for reduction:
     * if B used Y AND Y wasGeneratedBy A then B informedBy A     
     */
    public void putReducedNodesInAdjacencyMatrix(){
        for (int i = 0; i<adjacencyMatrix.length;i++){
            for (int j = 0; j<adjacencyMatrix.length;j++){
                if((adjacencyMatrix[i][j]!=null)&&(adjacencyMatrix[i][j].equals(GeneralConstants.USAGE_DEPENDENCY))){
                    //the adjacency matrix is initialized to null
                    for(int k = 0; k<adjacencyMatrix.length;k++){
                        if((adjacencyMatrix[j][k]!=null) && (adjacencyMatrix[j][k].equals(GeneralConstants.GENERATION_DEPENDENCY))){
                            adjacencyMatrix[i][k] = GeneralConstants.INFORM_DEPENDENCY; 
                        }
                    }
                }
            }
        }
    }

    /**
     * Method used to determine whether one of the types in the adjacency graph is of type URIType
     * @param currentURIType
     * @return true if the type is included as a type of one of the nodes
     */
    public boolean containsURIType(String URIType) {
        Iterator it = URIs.iterator();
        while(it.hasNext()){
            //check if any of the node types are of type URIType
            String currentURI = (String) it.next();
            if(this.nodes.get(currentURI).getType().equals(URIType))return true;
        }
        return false;
    }

    /**
     * Method which determines if a graph is the same as other.
     * Source and target edges must have the same URIs and in the same order.
     * @param target target graph to be compared with
     * @return 
     */
    //this has to be redone checking the connections to ensure removing ALL duplicates
    public boolean equalsGraph(Graph target) {
        //the number of nodes of both graphs have to be the same
        if(this.getNumberOfNodes()!=target.getNumberOfNodes()) return false;
        /*Old code: assumes the adj matrix and uris of both graphs are the same.
        However we could have graphs with different URIs which could be the same*/
//        ArrayList<String> targetURIs = target.getURIs();
//        for(int i=0; i< URIs.size();i++){
//            if(!nodes.get(URIs.get(i)).getType().equals(target.getNodes().get(targetURIs.get(i)).getType()))return false;
//        }
//        if(adjacencyMatrix!=null){
//            String[][] targetMatrix = target.getAdjacencyMatrix();
//            // I assume that the same graphs will have the same adj matrix (as they are read in the same order)
//            for(int i=0; i< adjacencyMatrix.length;i++){
//                for(int j=0; j< adjacencyMatrix.length;j++){
//                    if (adjacencyMatrix[i][j]!=null && targetMatrix[i][j] == null) return false;
//                    if (adjacencyMatrix[i][j]==null && targetMatrix[i][j] != null) return false;
//                    if (adjacencyMatrix[i][j]!=null && targetMatrix[i][j] != null && !adjacencyMatrix[i][j].equals(targetMatrix[i][j])){
//
//                        return false;
//                    }
//                }
//            }
//        }
//        return true;
        /*end of old code*/
        return(allConnectionsIncludedInGraph(this, target) && allConnectionsIncludedInGraph(target, this));
    }
    
    private static boolean allConnectionsIncludedInGraph(Graph source, Graph target){
        //for each one of the connections in the adj matrix, look for
        //ONE connection in the target Graph. For each of the connections of the adj matrix of the 
        //target graph, look for one connection in the original graph. If this happens for both,
        //they are equal.
        int length = source.getAdjacencyMatrix().length;//all matrixes are square and the same size (otherwise it is false)
        String [][] sourceAdjMatrix = source.getAdjacencyMatrix();
        boolean[][] boolMatrix = new boolean[length][length];
        source.initializeBoolMatrixToFalse(boolMatrix);
        String [][] targetMatrix = target.getAdjacencyMatrix();
        String typeI, typeJ, typeL, typeK;
        //initialize bool matrix to false. Each bool mean which connections have been used.
        //It is necessary in case we have multiple connections of the same types with differen uris.
        if(sourceAdjMatrix!=null){
            for(int i=0; i< length;i++){
                for(int j=0; j< length;j++){
                    if(sourceAdjMatrix[i][j]!=null && sourceAdjMatrix[i][j].equals(GeneralConstants.INFORM_DEPENDENCY)){
                        //for each connection in the adj matrix, check if exists in the other graph
                        int k=0;
                        boolean connFound = false;
                        while(k<length && !connFound){
                            int l=0; 
                            while(l<length && !connFound){
                                if(!boolMatrix[k][l] && 
                                    targetMatrix[k][l]!=null && 
                                    targetMatrix[k][l].equals(GeneralConstants.INFORM_DEPENDENCY)){
                                    //is type of i==type of k? is type of j == type of l? If yes and that connection
                                    //has not been checked already, then we are fine
                                    typeI = source.getNodes().get(source.getURIs().get(i-1)).getType();
                                    typeJ = source.getNodes().get(source.getURIs().get(j-1)).getType();
                                    typeK = target.getNodes().get(target.getURIs().get(k-1)).getType();
                                    typeL = target.getNodes().get(target.getURIs().get(l-1)).getType();
                                    if(typeI.equals(typeK) && typeJ.equals(typeL)){
                                        connFound = true;
                                        boolMatrix[k][l] = true;
                                    }
                                }
                                l++;
                            }
                            k++;
                        }
                        if(!connFound)return false;
                    }
                }
            }
            return true;
        }
        return false;
    }
    
    private void initializeBoolMatrixToFalse(boolean[][] boolMatrix){
        for (int i=0; i<boolMatrix.length; i++){
            for(int j=0; j<boolMatrix.length; j++){
                boolMatrix[i][j] = false;
            }
        }
    }
    
    
    
}
