#!/bin/sh

BASEDIR=`dirname $0`
# ----------


### EDIT --- your code here
# e.g. $BASEDIR/merge.sh -files=$INPUTS1 -threshold=$INPUTS2 > $OUTPUTS1
# using $BASEDIR/scriptname... is a good idea, since this script shall
# be able to run anywhere, i.e., not depend on a specific path.
# Note: if one of the arguments is a collection of size N, then the
# respective script variable (e.g., $INPUTS1) contains as its value a
# space separated list of N elements (e.g., "File1 File2 File3").

args=("$@")
  valueCounter=0
  arg1=""
  for arg in $@; do
    valueCounter=`expr $valueCounter + 1`
	if [ "$arg" == "-i1" ]; then GraphDatabase=${args[$valueCounter]}; fi
	if [ "$arg" == "-o1" ]; then FragmentFile=${args[$valueCounter]}; fi
	if [ "$arg" == "-o2" ]; then OccurrencesFile=${args[$valueCounter]}; fi
  done

  
/opt/tools/subdue/subdue -iterations 0 -nsubs 1 -eval 2 -out $FragmentFile $GraphDatabase
mv ${FragmentFile}_occurrences $OccurrencesFile


###  ------------------

# IGNORE report any errors
if [ $? -ne 0 ]; then 
    echo "Error"
    exit 1;
fi
